apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-product
  namespace: beautybay-product
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-product
  template:
    metadata:
      labels:
        app: nginx-product
    spec:
      containers:
        - name: nginx
          image: nginx:latest
          ports:
            - containerPort: 80
          volumeMounts:  # Add this inside the container spec
            - name: nginx-config
              mountPath: /etc/nginx/conf.d/default.conf  # Overrides default NGINX config
              subPath: nginx-product.conf  # File name in the ConfigMap
      volumes:  # Add this at the same level as containers, within `spec.template.spec`
        - name: nginx-config
          configMap:
            name: nginx-product-config  # Ensure this matches the ConfigMap name
