apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-product
  namespace: beautybay-product
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-product
  template:
    metadata:
      labels:
        app: nginx-product
    spec:
      containers:
        - name: nginx
          image: nginx:latest
          ports:
            - containerPort: 80
          volumeMounts:
            - name: nginx-config
              mountPath: /etc/nginx/conf.d/default.conf
              subPath: nginx-product.conf
      volumes:
        - name: nginx-config
          configMap:
            name: nginx-product-config  # Make sure this matches the ConfigMap name in 'beautybay-product'
