apiVersion: v1
kind: Service
metadata:
  name: kong-proxy
  namespace: default
spec:
  type: NodePort
  selector:
    app: kong
  ports:
    - name: http
      protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort: 32000  # Local port to access Kong HTTP
    - name: https
      protocol: TCP
      port: 8443
      targetPort: 8443
      nodePort: 32443  # Local port to access Kong HTTPS
