apiVersion: apps/v1
kind: Deployment
metadata:
  name: kong
  namespace: kong
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kong
  template:
    metadata:
      labels:
        app: kong
    spec:
      containers:
        - name: kong
          image: kong/kong:latest
          env:
            - name: KONG_DATABASE
              value: "postgres"
            - name: KONG_PG_HOST
              value: "postgres-postgresql.kong.svc.cluster.local"
            - name: KONG_PG_USER
              value: "kong"
            - name: KONG_PG_PASSWORD
              value: "nYZqWJPgHw"
            - name: KONG_PG_DATABASE
              value: "kong"
          ports:
            - containerPort: 8000
            - containerPort: 8001
            - containerPort: 8443
            - containerPort: 8444