apiVersion: v1
kind: Service
metadata:
  name: kong-gateway
  namespace: default  # Replace with your namespace if different
  annotations:
    konghq.com/protocol: "http"
spec:
  type: NodePort
  selector:
    app: kong
  ports:
    - name: proxy-http
      protocol: TCP
      port: 80           # Expose HTTP on port 80
      targetPort: 8000   # Map to Kong's HTTP port
      nodePort: 30080    # Choose a custom NodePort (adjust if needed)
    - name: proxy-https
      protocol: TCP
      port: 443          # Expose HTTPS on port 443
      targetPort: 8443   # Map to Kong's HTTPS port
      nodePort: 30443    # Choose a custom NodePort (adjust if needed)
