# postgres-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kong-postgres
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kong-postgres
  template:
    metadata:
      labels:
        app: kong-postgres
    spec:
      containers:
        - name: postgres
          image: postgres:13
          env:
            - name: POSTGRES_USER
              value: kong
            - name: POSTGRES_DB
              value: kong
            - name: POSTGRES_PASSWORD
              value: kongpassword
          ports:
            - containerPort: 5432

---
apiVersion: v1
kind: Service
metadata:
  name: kong-postgres
  namespace: default
spec:
  type: ClusterIP
  ports:
    - port: 5432
  selector:
    app: kong-postgres
